const BUY_CATEGORIES=["Sport","Vêtements","Maison","Tech","Beauté / santé","Événements","Voyages","Cadeaux","Autres"];
const SELL_CATEGORIES=["Vêtements","Sport","Maison","Tech","Livres","Accessoires","Autres"];
const BUY_STATUSES=[["idea","💡 Idée"],["model_found","🔎 Modèle trouvé — en cours"],["waiting_price","💰 En attente d’un bon prix"],["buy_soon","🔥 À acheter vite"],["purchased","✅ Acheté"],["abandoned","❌ Abandonné"]];
const SELL_STATUSES=[["to_sell","À vendre"],["estimate","À estimer"],["draft","Annonce à créer"],["listed","En ligne"],["reserved","Réservé"],["sold","Vendu"],["abandoned","Abandonné"]];
let sb,currentUser=null,items=[],people=[],currentView="dashboard",buyStatusFilter="",sellStatusFilter="";
const $=id=>document.getElementById(id);const money=n=>n==null||n===""?"":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(Number(n));const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function statusLabel(type,status){const a=type==="sell"?SELL_STATUSES:BUY_STATUSES;return(a.find(x=>x[0]===status)||["",status])[1]}
function categoryEmoji(c){return({"Sport":"🏃","Vêtements":"👕","Maison":"🏠","Tech":"💻","Beauté / santé":"✨","Événements":"🎟️","Voyages":"✈️","Cadeaux":"🎁","Livres":"📚","Accessoires":"👜","Autres":"•"}[c]||"•")}
function priorityBadge(p){if(p==="high")return'<span class="badge red">Priorité haute</span>';if(p==="low")return'<span class="badge">Priorité faible</span>';return""}
function itemCard(it){const person=people.find(p=>p.id===it.person_id),title=it.model_name||it.title,preview=it.preview_image_url?`<img src="${esc(it.preview_image_url)}" alt="">`:`<span>${categoryEmoji(it.category)}</span>`,price=it.item_type==="sell"?it.sale_asking_price:it.last_seen_price,target=it.item_type==="sell"?it.sale_min_price:it.target_price,secondary=[it.category,person?.name,it.merchant||it.sale_platform].filter(Boolean).join(" · ");return`<article class="item-card" data-id="${it.id}"><div class="thumb">${preview}</div><div class="item-main"><div class="item-title">${esc(title)}</div><div class="item-sub">${esc(secondary||it.title)}</div><div class="meta-row"><span class="badge ${["purchased","sold"].includes(it.status)?"green":""}">${esc(statusLabel(it.item_type,it.status))}</span>${priorityBadge(it.priority)}</div></div><div class="price-box">${price!=null?`<div class="price">${money(price)}</div>`:""}${target!=null?`<div class="price-target">${it.item_type==="sell"?"min.":"cible"} ${money(target)}</div>`:""}</div></article>`}
function empty(t){return`<div class="empty">${esc(t)}</div>`}
async function init(){const c=window.APP_CONFIG||{};if(!c.SUPABASE_URL||!c.SUPABASE_PUBLISHABLE_KEY||c.SUPABASE_URL.includes("COLLE_ICI")){$("authMessage").textContent="Renseigne d’abord config.js avec ton Project URL et ta Publishable key Supabase.";return}sb=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY);const{data:{session}}=await sb.auth.getSession();if(session?.user)await enterApp(session.user);sb.auth.onAuthStateChange(async(_,s)=>{if(s?.user&&!currentUser)await enterApp(s.user);if(!s?.user&&currentUser)exitApp()})}
async function enterApp(u){currentUser=u;$("authView").classList.add("hidden");$("appView").classList.remove("hidden");$("userEmail").textContent=u.email||"";await reloadAll()}
function exitApp(){currentUser=null;items=[];people=[];$("appView").classList.add("hidden");$("authView").classList.remove("hidden")}
async function reloadAll(){const[p,i]=await Promise.all([sb.from("people").select("*").order("name"),sb.from("items").select("*").order("created_at",{ascending:false})]);if(p.error)toast("Erreur personnes : "+p.error.message);if(i.error)toast("Erreur items : "+i.error.message);people=p.data||[];items=i.data||[];renderAll()}
function renderAll(){renderDashboard();renderBuy();renderPeople();renderGifts();renderSell()}
function renderDashboard(){const b=items.filter(i=>i.item_type==="buy");$("countIdeas").textContent=b.filter(i=>i.status==="idea").length;$("countModels").textContent=b.filter(i=>i.status==="model_found").length;$("countWaiting").textContent=b.filter(i=>i.status==="waiting_price").length;$("countUrgent").textContent=b.filter(i=>i.status==="buy_soon").length;const a=b.filter(i=>!["purchased","abandoned"].includes(i.status)).slice(0,4);$("dashboardItems").innerHTML=a.length?a.map(itemCard).join(""):empty("Aucune envie pour l’instant.");$("peoplePreview").innerHTML=people.length?people.slice(0,8).map(p=>{const c=items.filter(i=>i.item_type==="buy"&&i.category==="Cadeaux"&&i.person_id===p.id&&!["purchased","abandoned"].includes(i.status)).length;return`<button class="person-pill" data-person="${p.id}"><div class="person-avatar">${esc(p.name.slice(0,1).toUpperCase())}</div><strong>${esc(p.name)}</strong><div class="tiny muted">${c} idée${c>1?"s":""}</div></button>`}).join(""):empty("Ajoute les personnes pour lesquelles tu cherches des cadeaux.");wireCards()}
function renderBuy(){const q=$("buySearch").value.trim().toLowerCase();let l=items.filter(i=>i.item_type==="buy");if(buyStatusFilter)l=l.filter(i=>i.status===buyStatusFilter);if(q)l=l.filter(i=>[i.title,i.model_name,i.category,i.notes,i.merchant].some(v=>String(v||"").toLowerCase().includes(q)));$("buyItems").innerHTML=l.length?l.map(itemCard).join(""):empty("Aucun achat avec ces filtres.");wireCards()}
function renderSell(){const q=$("sellSearch").value.trim().toLowerCase();let l=items.filter(i=>i.item_type==="sell");if(sellStatusFilter)l=l.filter(i=>i.status===sellStatusFilter);if(q)l=l.filter(i=>[i.title,i.category,i.notes,i.sale_platform].some(v=>String(v||"").toLowerCase().includes(q)));$("sellItems").innerHTML=l.length?l.map(itemCard).join(""):empty("Aucune vente pour l’instant.");wireCards()}
function renderPeople(){$("peopleList").innerHTML=people.length?people.map(p=>{const c=items.filter(i=>i.person_id===p.id&&i.category==="Cadeaux").length;return`<div class="person-row"><div class="person-avatar">${esc(p.name.slice(0,1).toUpperCase())}</div><div class="grow"><strong>${esc(p.name)}</strong><div class="tiny muted">${c} idée${c>1?"s":""} cadeau</div></div><button class="link-btn" data-person-filter="${p.id}">Voir</button></div>`}).join(""):empty("Aucune personne ajoutée.")}
function renderGifts(personId=""){let l=items.filter(i=>i.item_type==="buy"&&i.category==="Cadeaux");if(personId)l=l.filter(i=>i.person_id===personId);$("giftItems").innerHTML=l.length?l.map(itemCard).join(""):empty("Aucune idée cadeau.");wireCards()}
function wireCards(){document.querySelectorAll(".item-card").forEach(el=>el.onclick=()=>openItem(el.dataset.id));document.querySelectorAll("[data-person]").forEach(el=>el.onclick=()=>{switchView("gifts");renderGifts(el.dataset.person)})}
function switchView(v){currentView=v;document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(v+"View").classList.add("active");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("pageTitle").textContent={dashboard:"Mes envies",buy:"Mes achats",gifts:"Cadeaux",sell:"Mes ventes",profile:"Profil"}[v]||"Mes envies";$("addButton").classList.toggle("hidden",v==="profile")}
function fillCategories(type,selected){const a=type==="sell"?SELL_CATEGORIES:BUY_CATEGORIES;$("itemCategory").innerHTML=a.map(c=>`<option ${c===selected?"selected":""}>${esc(c)}</option>`).join("")}
function fillStatuses(type,selected){const a=type==="sell"?SELL_STATUSES:BUY_STATUSES;$("itemStatus").innerHTML=a.map(([v,l])=>`<option value="${v}" ${v===selected?"selected":""}>${esc(l)}</option>`).join("")}
function fillPeople(selected){$("itemPerson").innerHTML=`<option value="">—</option>`+people.map(p=>`<option value="${p.id}" ${p.id===selected?"selected":""}>${esc(p.name)}</option>`).join("")}
function refreshDynamicFields(){const t=$("itemType").value,c=$("itemCategory").value;$("personField").classList.toggle("hidden",!(t==="buy"&&c==="Cadeaux"));$("saleFields").classList.toggle("hidden",t!=="sell");$("modelFields").classList.toggle("hidden",t!=="buy")}
function openNew(type=currentView==="sell"?"sell":"buy"){$("itemForm").reset();$("itemId").value="";$("itemType").value=type;fillCategories(type,type==="buy"?"Sport":"Vêtements");fillStatuses(type,type==="buy"?"idea":"to_sell");fillPeople("");$("itemPriority").value="normal";$("deleteItemButton").classList.add("hidden");$("itemDialogEyebrow").textContent=type==="buy"?"NOUVELLE IDÉE":"NOUVELLE VENTE";$("itemDialogTitle").textContent=type==="buy"?"Ajouter une envie":"Ajouter un objet à vendre";refreshDynamicFields();$("itemDialog").showModal()}
function openItem(id){const it=items.find(x=>x.id===id);if(!it)return;$("itemId").value=it.id;$("itemType").value=it.item_type;fillCategories(it.item_type,it.category);fillStatuses(it.item_type,it.status);fillPeople(it.person_id||"");$("itemTitle").value=it.title||"";$("itemPriority").value=it.priority||"normal";$("itemNotes").value=it.notes||"";$("itemModelName").value=it.model_name||"";$("itemProductUrl").value=it.product_url||"";$("itemPreviewImage").value=it.preview_image_url||"";$("itemLastPrice").value=it.last_seen_price??"";$("itemTargetPrice").value=it.target_price??"";$("itemMerchant").value=it.merchant||"";$("salePlatform").value=it.sale_platform||"";$("saleListingUrl").value=it.sale_listing_url||"";$("saleAskingPrice").value=it.sale_asking_price??"";$("saleMinPrice").value=it.sale_min_price??"";$("deleteItemButton").classList.remove("hidden");$("itemDialogEyebrow").textContent=it.item_type==="buy"?"ACHAT":"VENTE";$("itemDialogTitle").textContent=it.model_name||it.title;refreshDynamicFields();$("itemDialog").showModal()}
function numOrNull(v){return v===""?null:Number(v)}
async function saveItem(e){e.preventDefault();const id=$("itemId").value,type=$("itemType").value,old=items.find(i=>i.id===id);const p={user_id:currentUser.id,item_type:type,title:$("itemTitle").value.trim(),category:$("itemCategory").value,person_id:(type==="buy"&&$("itemCategory").value==="Cadeaux"&&$("itemPerson").value)?$("itemPerson").value:null,status:$("itemStatus").value,priority:$("itemPriority").value,notes:$("itemNotes").value.trim()||null,model_name:type==="buy"?($("itemModelName").value.trim()||null):null,product_url:type==="buy"?($("itemProductUrl").value.trim()||null):null,preview_image_url:type==="buy"?($("itemPreviewImage").value.trim()||null):null,merchant:type==="buy"?($("itemMerchant").value.trim()||null):null,last_seen_price:type==="buy"?numOrNull($("itemLastPrice").value):null,target_price:type==="buy"?numOrNull($("itemTargetPrice").value):null,sale_platform:type==="sell"?($("salePlatform").value.trim()||null):null,sale_listing_url:type==="sell"?($("saleListingUrl").value.trim()||null):null,sale_asking_price:type==="sell"?numOrNull($("saleAskingPrice").value):null,sale_min_price:type==="sell"?numOrNull($("saleMinPrice").value):null};let r=id?await sb.from("items").update(p).eq("id",id).select().single():await sb.from("items").insert(p).select().single();if(r.error){toast("Erreur : "+r.error.message);return}const saved=r.data,newPrice=saved.last_seen_price,oldPrice=old?.last_seen_price;if(type==="buy"&&newPrice!=null&&(!id||Number(newPrice)!==Number(oldPrice))){await sb.from("price_history").insert({user_id:currentUser.id,item_id:saved.id,price:newPrice})}$("itemDialog").close();toast(id?"Modifié":"Ajouté");await reloadAll()}
async function deleteItem(){const id=$("itemId").value;if(!id)return;if(!confirm("Supprimer définitivement cet élément ?"))return;const{error}=await sb.from("items").delete().eq("id",id);if(error){toast("Erreur : "+error.message);return}$("itemDialog").close();toast("Supprimé");await reloadAll()}
async function addPerson(e){e.preventDefault();const name=$("personName").value.trim();if(!name)return;const{error}=await sb.from("people").insert({user_id:currentUser.id,name});if(error){toast("Erreur : "+error.message);return}$("personDialog").close();$("personForm").reset();toast("Personne ajoutée");await reloadAll()}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("authMessage").textContent="";if(!sb){$("authMessage").textContent="Configuration Supabase manquante.";return}const{error}=await sb.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error)$("authMessage").textContent=error.message.includes("Email not confirmed")?"Ton adresse email n’est pas encore confirmée. On pourra le faire après avoir configuré l’URL GitHub Pages.":error.message});
$("logoutButton").onclick=()=>sb.auth.signOut();$("addButton").onclick=()=>openNew();$("addPersonButton").onclick=()=>$("personDialog").showModal();$("itemForm").addEventListener("submit",saveItem);$("personForm").addEventListener("submit",addPerson);$("deleteItemButton").onclick=deleteItem;$("itemType").addEventListener("change",()=>{const t=$("itemType").value;fillCategories(t);fillStatuses(t);refreshDynamicFields()});$("itemCategory").addEventListener("change",refreshDynamicFields);$("buySearch").addEventListener("input",renderBuy);$("sellSearch").addEventListener("input",renderSell);document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>{const v=b.dataset.jump;if(v==="buy"&&b.dataset.statusFilter!==undefined){buyStatusFilter=b.dataset.statusFilter;document.querySelectorAll("#buyStatusChips .chip").forEach(c=>c.classList.toggle("active",c.dataset.status===buyStatusFilter))}switchView(v);if(v==="buy")renderBuy()});document.querySelectorAll("#buyStatusChips .chip").forEach(c=>c.onclick=()=>{buyStatusFilter=c.dataset.status;document.querySelectorAll("#buyStatusChips .chip").forEach(x=>x.classList.toggle("active",x===c));renderBuy()});document.querySelectorAll("#sellStatusChips .chip").forEach(c=>c.onclick=()=>{sellStatusFilter=c.dataset.status;document.querySelectorAll("#sellStatusChips .chip").forEach(x=>x.classList.toggle("active",x===c));renderSell()});document.addEventListener("click",e=>{const p=e.target.closest("[data-person-filter]");if(p)renderGifts(p.dataset.personFilter)});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));init();
